MODEL_LIST = [
                # "/mnt/datayuliangyan/meta-llama/Meta-Llama-3-8B/",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3-8B-Instruct/",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3.1-8B/",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3.1-8B-Instruct/",
              # "/mnt/data/yuliangyan/mistralai/Mistral-7B-v0.1/",
              "/mnt/data/haochuntang/mistralai/Mistral-7B-Instruct-v0.1",
            #   "/home/yuliangyan/Code/llm-fingerprinting/stanford_alpaca/saved_models_mistral_test",
              # "/mnt/data/yuliangyan/deepseek-ai/deepseek-llm-7b-bsase/",
            #   "/home/yuliangyan/Code/llm-fingerprinting/stanford_alpaca/saved_models_deepseek_8_test",
              # "/mnt/data/yuliangyan/deepseek-ai/deepseek-llm-7b-chat/",
              # "/mnt/data/yuliangyan/deepseek-ai/deepseek-math-7b-instruct/",
              # "/mnt/data/yuliangyan/Qwen/Qwen2.5-7B/",
              # "/mnt/data/yuliangyan/microsoft/Phi-3-medium-4k-instruct",
              "/mnt/data/haochuntnag/google/gemma-2-2b",
              "/mnt/data/haochuntang/google/gemma-2-2b-it",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3-8B",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3-8B-Instruct",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3.1-8B",
              # "/mnt/data/yuliangyan/meta-llama/Meta-Llama-3.1-8B-Instruct",
              # "/mnt/data/yuliangyan/mistralai/Mistral-7B-v0.1",
              # "/mnt/data/yuliangyan/deepseek-ai/deepseek-llm-7b-base",
              # "/mnt/data/yuliangyan/deepseek-ai/deepseek-llm-7b-chat",
              # "/mnt/data/yuliangyan/Qwen/Qwen2.5-7B",
              # "/mnt/data/yuliangyan/microsoft/Phi-3-medium-4k-instruct",
              # "/mnt/data/yuliangyan/instruction_tuning_models/llama3-ft",
              # "/mnt/data/yuliangyan/instruction_tuning_models/llama3-instruct-ft",
              # "/mnt/data/yuliangyan/instruction_tuning_models/llama31-ft",
              # "/mnt/data/yuliangyan/instruction_tuning_models/mistral-ft",
              # "/mnt/data/yuliangyan/instruction_tuning_models/deepseek-ft",
              # "/mnt/data/yuliangyan/instruction_tuning_models/deepseek-chat-ft",
              ]


